/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.parqueo;

import com.mycompany.parqueo.DAO.Espacio_ParqueoDAO;
import com.mycompany.parqueo.DAO.Seccion_ParqueoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ale
 */
public class JF_SeleccionarCampo extends javax.swing.JFrame {
    Parqueo p = new Parqueo();
    Seccion_Parqueo sp = new Seccion_Parqueo();
    Espacio_Parqueo ep = new Espacio_Parqueo();
    Seccion_ParqueoDAO sp_DAO = new Seccion_ParqueoDAO();
    Espacio_ParqueoDAO ep_DAO = new Espacio_ParqueoDAO();
    List<Seccion_Parqueo> secParqueos;
    List<Espacio_Parqueo> ep1;
    /**
     * Creates new form JF_SeleccionarCampo
     */
    public JF_SeleccionarCampo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        cmbEspacio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbPiso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("SELECCIONE SU ESPACIO");

        btnConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        cmbEspacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspacioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Piso:");

        cmbPiso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campo 1", "Campo 2", "Campo 3", "Campo 4", "Campo 5", "Campo 6", "Campo 7", "Campo 8", "Campo 9", "Campo 10", "Campo 11", "Campo 12", "Campo 13", "Campo 14", "Campo 15", "Campo 16", "Campo 17", "Campo 18", "Campo 19", "Campo 20", "Campo 21", "Campo 22", "Campo 23", "Campo 24", "Campo 25", "Campo 26", "Campo 27", "Campo 28", "Campo 29", "Campo 30", "Campo 31", "Campo 32", "Campo 33", "Campo 34", "Campo 35", "Campo 36", "Campo 37", "Campo 38", "Campo 39", "Campo 40", "Campo 41", "Campo 42", "Campo 43", "Campo 44", "Campo 45", "Campo 46", "Campo 47", "Campo 48", "Campo 49", "Campo 50" }));
        cmbPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPisoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Espacio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(141, 141, 141))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(cmbEspacio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEspacioActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        JF_SeleccionarParqueo jsp = new JF_SeleccionarParqueo();
        try {
            jsp.actualizarCmbParqueo();
            jsp.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(JF_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //Existe cliente relacionado a la placa
        JF_BuscarParqueo jf = new JF_BuscarParqueo();
        jf.setVisible(true);
        jf.setParqueo(p);
        jf.setSeccion_Parqueo(sp);
        String x = cmbEspacio.getSelectedItem().toString();
        for (int i=0; i<ep1.size(); i++){
            if(ep1.get(i).getEspacio_Id() == Integer.parseInt(x)) {
                ep = ep1.get(i);
            }
        }
        jf.setEspacio_Parqueo(ep);
        dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void cmbPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPisoActionPerformed

    }//GEN-LAST:event_cmbPisoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            actualizarCmbEspacio();
        } catch (SQLException ex) {
            Logger.getLogger(JF_SeleccionarCampo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_SeleccionarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_SeleccionarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_SeleccionarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_SeleccionarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JF_SeleccionarCampo jf = new JF_SeleccionarCampo();
                jf.setVisible(true);
                try {
                    Parqueo p = new Parqueo();
                    p.setParqueo_Id(12);
                    jf.actualizarCmbPiso(p);
                } catch (SQLException ex) {
                    Logger.getLogger(JF_SeleccionarParqueo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void actualizarCmbPiso(Parqueo p) throws SQLException {
        this.p = p;
        //Parqueo p = new Parqueo();//Eliminar cuando se reciba el objeto Parqueo
        //p.setParqueo_Id(12);//Eliminar cuando se reciba el objeto Parqueo
        List<String> sp = new ArrayList<String>();
        secParqueos = new ArrayList<Seccion_Parqueo>();
        secParqueos = sp_DAO.usp_sel_totalSeccionParqueo(this.p);
        cmbPiso.removeAllItems();
        for (int i = 0; i < secParqueos.size(); i++) {
            cmbPiso.addItem(secParqueos.get(i).getDescripcion());
        }
    }
    
    public void actualizarCmbEspacio() throws SQLException {
        
        //Seccion_Parqueo sp = new Seccion_Parqueo();//Eliminar cuando se reciba el objeto Parqueo
        //sp.setSeccion_Id(1);//Eliminar cuando se reciba el objeto Parqueo
        
        //EL PROBLEMA ES QUE NO ESTA RECIBIENDO EL VALOR.
        if(cmbPiso.getSelectedItem().toString() == null) { return; }
        String x = cmbPiso.getSelectedItem().toString();
        for (int i=0; i<secParqueos.size(); i++){
            if(secParqueos.get(i).getDescripcion().equals(x)) {
                sp = secParqueos.get(i);
            }
        }
        List<String> ep = new ArrayList<String>();
        ep1 = new ArrayList<Espacio_Parqueo>();
        ep1 = ep_DAO.usp_selespacio_parqueo(this.sp);
        cmbEspacio.removeAllItems();
        for (int i = 0; i < ep1.size(); i++) {
            //cmbEspacio.addItem("Pos. "+ep1.get(i).getEspacio_Id());
            cmbEspacio.addItem(""+ep1.get(i).getEspacio_Id());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cmbEspacio;
    private javax.swing.JComboBox<String> cmbPiso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
